# k = v

student:
  name: qianjiang
  age: 3


# 行内写法

students: {name: qinjiang, age: 3}

# 数组
pets:
  - cat
  - dog
  - pig

petsother: [cat, dog, pig]


# yaml可以直接对实体类赋值

peopleBuyRecord:
  name: chen
  age: 2
  isBuy: true
  buytime: 2019/11/02
  maps: {k1: v1, k2: v2}
  lists:
    -code
    -music
    -girl
  createPeople:
    name: 我是新员工
    age: 10


